zenspider/enhanced-ruby-mode

- enh-ruby-mode.el
To quote the Emacs Lisp manual:
> Simply loading a package should not change Emacs's editing
> behavior. Include a command or commands to enable and disable the
> feature, or to invoke it.
> This convention is mandatory for any file that includes custom
> definitions.  If fixing such a file to follow this convention requires
> an incompatible change, go ahead and make the incompatible change;
> don't postpone it.
> Remove unexpected autoloads

- enh-ruby-mode.el
A fix for #73 
By default **enh-ruby-add-encoding-comment-on-save** is t.
> Added configuration option to toggle magic encoding comment

- enh-ruby-mode.el
Right now, any user that has `global-ethan-wspace-mode` turned on faces warnings when opening a `.rb` file in Enhanced Ruby Mode. This is because `enh-ruby-mode` sets `require-final-newline` to `t` locally, which interferes with ethan-wspace mode.
This suggested fix is similar to fixes for other various modes, including Ruby Mode, [Dockerfile Mode](https://github.com/spotify/dockerfile-mode/pull/10/files), [Cucumber Mode](https://github.com/michaelklishin/cucumber.el/pull/51) and many others.
For more about the motivation, [this thread](https://github.com/glasserc/ethan-wspace/issues/22) over at ethan-wspace provides a lot of discussion and background.
Falling back to `mode-require-final-newline` is preferred since users will be able to override that setting fairly easily.
> Set require-final-newline correctly.

- README.rdoc
People new to Emacs might not know how to properly setup enh-ruby-mode
for common Ruby files. These instructions aim to aid this problem.
> Add mode setup instructions to README

- enh-ruby-mode.el
Address #102.
Do not alias `prog-mode`; it breaks `derived-mode-p`, which a lot of other packages rely on.
See emacs-helm/helm#1704, for example.
> Derive from `prog-mode`

- enh-ruby-mode.el
Most importantly, the default script encoding in Ruby is now UTF-8, so `encoding: utf-8` is no longer necessary.
> Import the new default encoding map from ruby-mode

- enh-ruby-mode.el
Highlight Kernel methods and Module private methods.  These lists are stolen from ruby-mode.
> Highlight additional keywords

- ruby/erm_buffer.rb
- test/enh-ruby-mode-test.el
- test/test_erm_buffer.rb
Potential fix for #83 
Tested with ruby 2.4.0
> Fix indentation for leading dots (multi-line method chains)

- ruby/erm_buffer.rb
Thanks for the review!
Regarding the second hunk, can't do `tok` because that would shadow the `tok` outside. But I do agree that a simple `a[1]` is better.
> Minor code style fixes

- enh-ruby-mode.el
Whitout the comma, "languages elisp" was considered as a single keyword and the package was not listed in the package buffer when filtering by the "languages" keyword.
> Add a missing comma between keywords

- ruby/erm_buffer.rb
- test/enh-ruby-mode-test.el
- test/test_erm_buffer.rb
Fixes #131 and the note at the end of #128 
This adds handling for blocks and comments, but I feel like it's made worse by me not being able to understand the elisp side. Specifically, I also noticed that `do ... end` blocks messed up the indentation, but couldn't figure out what the output from ruby would have to be for elisp to indent correctly, and couldn't grok the elisp stuff to figure out what would have to change there.
PS. I really liked `debugging.md`, learned a few tricks.
> Fix misc leading dots indentation bugs

- enh-ruby-mode.el
Consider the following Ruby function. The Emacs cursor is represented by the pipe character:
```ruby
RSpec.describe Foo do
it 'bar' do
|    
end
end
```
By running `enh-ruby-beginning-of-block` twice, the cursor will be moved up to the first `do`. By running it a third time, the command will get stuck in an infinite loop. The same happens for `enh-ruby-end-of-block`.
This PR fixes the problem by breaking out of the loop if the cursor reaches either boundary of the buffer. With this fix, a third run will get the cursor to the very beginning of the file.
I've recently begun my deep adventures in Elisp, so I'm not sure if there's a better way to fix the issue. I would appreciate any directions :)
> Fix infinite loop in block movement functions

- enh-ruby-mode.el
- test/enh-ruby-mode-test.el
Issue: https://github.com/zenspider/enhanced-ruby-mode/issues/159
Before (with default settings):
```ruby
result =
list.map do |val|
val = do_something(val)
do_something_else(val)
end
variable
.method_a
.method_b {
do_something
do_something_else
}
.method_b do |e|
e = do_something(e)
broken?(e)
end
```
After (with default settings):
```ruby
result =
list.map do |val|
val = do_something(val)
do_something_else(val)
end
variable
.method_a
.method_b {
do_something
do_something_else
}
.method_b do |e|
e = do_something(e)
broken?(e)
end
```
> Handle block indentation on continued statements

- enh-ruby-mode.el
- test/enh-ruby-mode-test.el
Issue: https://github.com/zenspider/enhanced-ruby-mode/issues/160
Before:
```ruby
variable
.one
.two(
three,
four
)
.five
```
After:
```ruby
variable
.one
.two(
three,
four
)
.five
```
`(setq enh-ruby-bounce-deep-indent t)`
Before:
```ruby
variable
.one
.two(
three,
four
)
.five
```
After:
```ruby
variable
.one
.two(
three,
four
)
.five
```
I'm not a fan of this style, neither I've seen it elsewhere, but I tried to keep the behavior consistent. Please let me know if this is correct @zenspider
> Handle indentation of arguments and newlines on continued statements

- enh-ruby-mode.el
Hello!
Updated my packages today and got these warnings:
```
Warning (bytecomp): make-obsolete-variable called with 2 arguments, but requires 3-4
Warning (bytecomp): reference to free variable ‘erm-ruby-process’
Warning (bytecomp): reference to free variable ‘erm-parsing-p’
Warning (bytecomp): reference to free variable ‘erm-response’
Warning (bytecomp): assignment to free variable ‘erm-ruby-process’
Warning (bytecomp): reference to free variable ‘s’
```
The last one, `reference to free variable ‘s’`, was a bit of guesswork but I believe variable `FILENAME` is to be used in its place. More so, I wasn't sure if `(interactive "sgem which ")` should be corrected to `(interactice "gem which")` so I didn't change it.
There was one more warning which I didn't look at: `Warning (bytecomp): the …
> Fix (some) compilation warnings

- ruby/erm_buffer.rb
This adds support for the case-in construct introduced in Ruby 2.7.
> Add support for the "in" clause of Ruby 2.7

- Rakefile
Always start with a vanilla Emacs configuration. Helps to ensure that
the user's Emacs configuration doesn't interfere with tests or byte
compilation.
> Always pass -Q to emacs in Rakefile

- enh-ruby-mode.el
It is elisp best practice to use sharp quotes for functions. It give a
hint to the byte-compiler that the symbol references as function. If the
function is undefined, the byte compiler will emit a warning.
This is documented in the "The Emacs Lisp Style Guide":
https://github.com/bbatsov/emacs-lisp-style-guide#functions
> Use a sharp quote (`#'`) when quoting function names. It’s a good hint
> for the byte-compiler, which will warn you if the function is
> undefined.
> Use sharp quotes when quoting functions

- Rakefile
- test/enh-ruby-mode-test.el
- test/helper.el
Compiling the elisp files exposes several warnings that have now been
cleaned up. Running this regularly will help ensure the warnings don't
return.
emacs -Q --batch -f batch-byte-compile enh-ruby-mode.el
emacs -Q --batch -f batch-byte-compile test/enh-ruby-mode-test.el
In toplevel form:
test/enh-ruby-mode-test.el:22:14:Warning: reference to free variable
‘enh-ruby-backward-sexp-test’
test/enh-ruby-mode-test.el:30:14:Warning: reference to free variable
‘enh-ruby-backward-sexp-test-inner’
test/enh-ruby-mode-test.el:40:14:Warning: reference to free variable
‘enh-ruby-forward-sexp-test’
test/enh-ruby-mode-test.el:48:14:Warning: reference to free variable
‘enh-ruby-up-sexp-test’
test/enh-ruby-mode-test.el:56:14:Warning: reference to free variable
‘enh-ruby-end-of-defun’ …
> Compile all "*.el" during "compile" rake task

- README.rdoc
This follows an Emacs best practice of matching the end of the string,
not the end of a line, in auto-mode-alist.
For additional details, see:
https://www.emacswiki.org/emacs/AutoModeAlist
> Note that `\'` matches the end of a string, whereas `$` matches the
> empty string before a newline. Thus, `$` may lead to unexpected
> behavior when dealing with filenames containing newlines. (Should be
> pretty rare… ;))
> Use \\' in auto-mode-alist regular expressions
